"""Canonical board-geometry package.

This package is the single home for board-owned geometry concepts:

- explicit geometry zones
- board geometry containers
- symbolic geometry notation bindings
- local geometry mutation models
- overlap resolution
"""

from signalflow.board.geometry.continuity import (
    TopologyContinuityExpr,
    TopologyContinuityFamily,
    extraRingContinuityFamily_build,
)
from signalflow.board.geometry.coupling import (
    GeometryCollectionOperand,
    GeometryCouplingApplied,
    GeometryCouplingExpr,
    GeometryCouplingFamily,
    GeometryCouplingOp,
    GeometryCouplingSymbolicExpr,
    GeometryCouplingZoneOperand,
    GeometryDependentKind,
    GeometryDependentRef,
    GeometryModuleOperand,
    chipTerminalCouplingAppliedResult_build,
    chipTerminalCouplingFamilyResult_build,
    chipTerminalCouplingSymbolicExprsResult_build,
    geometryCouplingAppliedResult_build,
    geometryCouplingExpr_buildFromSymbolic,
    zoneCouplingOperandResult_build,
    zoneCouplingOperandsResult_build,
)
from signalflow.board.geometry.doctrine import (
    ZoneOverlapExprBank,
    eastWestZoneOverlapExprBank_build,
)
from signalflow.board.geometry.expr import (
    GeometryAxis,
    ZoneConnectivityKind,
    ZoneFace,
    ZoneGeometryTarget,
    ZoneMutationExpr,
    ZoneMutationKind,
    ZoneRelationExpr,
    ZoneRelationKind,
    zoneExtentMaxAlignRelation_build,
    zoneExtentSetMutation_build,
    zoneMinClearanceRelation_build,
    zonePaddingAddMutation_build,
    zoneShiftApplyMutation_build,
)
from signalflow.board.geometry.interpreter import (
    ContinuityViolation,
    LocalGeometryInterpreter,
    LocalGeometryMutation,
    LocalInterpreterResult,
    wteLocalGeometryInterpreter_build,
)
from signalflow.board.geometry.mutation import (
    ZoneAdjacencyConstraint,
    ZoneGeometryMutation,
    ZoneGeometrySelector,
    boardRegionIdResult_fromSfN,
    zoneAdjacencyConstraint_buildFromExpr,
    zoneAdjacencyConstraintResult_buildFromExpr,
    zoneGeometryMutation_buildFromExpr,
    zoneGeometrySelector_buildFromTarget,
    zoneMutationResult_buildFromExpr,
    zoneSelectorResult_buildFromTarget,
)
from signalflow.board.geometry.repair import (
    ContinuityRepairPass,
    ContinuityRepairPlan,
    LocalGeometryStretch,
    wteContinuityRepairPass_build,
)
from signalflow.board.geometry.symbolic import (
    GeometryExpr,
    GeometryExprOp,
    GeometryExprRhs,
    GeometryOp,
    GeometryOpLike,
    GeometryRhs,
    RegionOperand,
    ZoneOperand,
    geometryExprLoweredResult_build,
    zoneOperandResult_build,
    zoneOperandsResult_build,
    zoneOpResult_build,
)
from signalflow.board.geometry.georules import (
    GeoArg,
    GeoArgScalar,
    GeoArgScaled,
    GeoChange,
    GeoEffect,
    GeoOp,
    RuleBank,
    RuleEntry,
    RULES,
    TopologyFace,
    geometry_change,
    rules_apply,
)
from signalflow.board.geometry.topology import (
    BoardTopologySchema,
    ContinuityGroup,
    TopologyFamily,
    wteZoneBoardTopologySchema_build,
)
from signalflow.board.geometry.zones import (
    BoardGeometry,
    GeometryZone,
    regionByName_get,
)

__all__ = [
    "BoardGeometry",
    "BoardTopologySchema",
    "ContinuityGroup",
    "ContinuityRepairPass",
    "ContinuityRepairPlan",
    "ContinuityViolation",
    "LocalGeometryStretch",
    "LocalGeometryInterpreter",
    "LocalGeometryMutation",
    "LocalInterpreterResult",
    "TopologyContinuityExpr",
    "TopologyContinuityFamily",
    "GeoArg",
    "GeoArgScalar",
    "GeoArgScaled",
    "GeoChange",
    "GeoEffect",
    "GeoOp",
    "RuleBank",
    "RuleEntry",
    "RULES",
    "TopologyFace",
    "TopologyFamily",
    "geometry_change",
    "rules_apply",
    "extraRingContinuityFamily_build",
    "wteLocalGeometryInterpreter_build",
    "wteContinuityRepairPass_build",
    "wteZoneBoardTopologySchema_build",
    "GeometryCollectionOperand",
    "GeometryAxis",
    "GeometryCouplingApplied",
    "GeometryCouplingExpr",
    "GeometryCouplingFamily",
    "GeometryCouplingOp",
    "GeometryCouplingSymbolicExpr",
    "GeometryCouplingZoneOperand",
    "GeometryDependentKind",
    "GeometryDependentRef",
    "GeometryExpr",
    "GeometryExprOp",
    "GeometryExprRhs",
    "GeometryOp",
    "GeometryOpLike",
    "GeometryRhs",
    "GeometryZone",
    "GeometryModuleOperand",
    "RegionOperand",
    "ZoneAdjacencyConstraint",
    "ZoneConnectivityKind",
    "ZoneFace",
    "ZoneGeometryMutation",
    "ZoneGeometrySelector",
    "ZoneGeometryTarget",
    "ZoneMutationExpr",
    "ZoneMutationKind",
    "ZoneOperand",
    "ZoneOverlapExprBank",
    "ZoneRelationExpr",
    "ZoneRelationKind",
    "boardRegionIdResult_fromSfN",
    "zoneSelectorResult_buildFromTarget",
    "zoneMutationResult_buildFromExpr",
    "zoneAdjacencyConstraintResult_buildFromExpr",
    "chipTerminalCouplingAppliedResult_build",
    "chipTerminalCouplingFamilyResult_build",
    "chipTerminalCouplingSymbolicExprsResult_build",
    "eastWestZoneOverlapExprBank_build",
    "geometryCouplingAppliedResult_build",
    "geometryCouplingExpr_buildFromSymbolic",
    "geometryExprLoweredResult_build",
    "regionByName_get",
    "zoneExtentMaxAlignRelation_build",
    "zoneExtentSetMutation_build",
    "zoneMinClearanceRelation_build",
    "zonePaddingAddMutation_build",
    "zoneShiftApplyMutation_build",
    "zoneAdjacencyConstraint_buildFromExpr",
    "zoneCouplingOperandResult_build",
    "zoneCouplingOperandsResult_build",
    "zoneGeometryMutation_buildFromExpr",
    "zoneGeometrySelector_buildFromTarget",
    "zoneOpResult_build",
    "zoneOperandResult_build",
    "zoneOperandsResult_build",
]
