"""Shared canonical models for SignalFlow.

This package holds the typed vocabulary intended to be consumed across
SignalFlow subsystems.

Key components:
    - ChipId / ChipRef / Chip: First-class chip vocabulary
    - DiagnosticLevel / DiagnosticPhase: Structured diagnostic vocabulary
    - Diagnostic / DiagnosticSet / DiagnosticStack: Diagnostics models
    - EngineName: Explicit engine selector for render dispatch
    - RoutingZone / RoutingZoneInterconnect / RoutingZoneGrid: World-topology models
    - RoutingZoneRegion / RoutingZoneRegionSet: Explicit zone-owned region geometry
    - Result / ResultOk / ResultErr: Explicit success/failure control flow
"""
from __future__ import annotations

from signalflow.models.assignment import (
    RoutingZoneAssignment,
    RoutingZoneAssignmentSet,
    RoutingZoneLayer,
    RoutingZoneLayerSet,
    routingZoneAssignmentSetResult_build,
    routingZoneLayerSetResult_build,
    routingZoneLayerSetResult_buildFromCircuitDocument,
)
from signalflow.models.cardinal_side import CardinalSide
from signalflow.models.chip import (
    Chip,
    ChipId,
    ChipInternalWiringDirective,
    ChipInternalWiringDirectiveSet,
    ChipIo,
    ChipIoInput,
    ChipIoInternalWiring,
    ChipPortDeclaration,
    ChipPortDeclarationSet,
    ChipRef,
    ChipTerminal,
    ChipTerminalSet,
    ChipTerminalSide,
    chipDrawLines_build,
    chipInternalWiringDirectiveResult_build,
    chipInternalWiringDirectiveSetResult_build,
    chipPortDeclarationResult_build,
    chipPortDeclarationSetResult_build,
    chipResult_build,
    chipTerminalSetResult_build,
)
from signalflow.models.chip_endpoint import ChipTerminalRef, chipTerminalRef_build
from signalflow.models.chip_route import (
    ChipInternalRouteClass,
    ChipInternalRouteDirectiveSpec,
    ChipInternalRouteOrientation,
    ChipInternalRouteSemantics,
    ChipInternalRouteSolveKind,
    ChipInternalSolvedRoute,
    ChipInternalSolvedRouteSet,
    chipInternalRouteDirectiveSpecResult_build,
    chipInternalSolvedRouteResult_build,
    chipInternalSolvedRouteSetResult_build,
)
from signalflow.models.circuit import (
    CircuitCall,
    CircuitCallSet,
    CircuitChipSet,
    CircuitDocument,
    circuitCallSetResult_build,
    circuitChipSetResult_build,
    circuitDocumentResult_build,
)
from signalflow.models.circuit_source import (
    CircuitChipIoInputSource,
    CircuitChipIoInternalWiringSource,
    CircuitChipIoSource,
    CircuitDocumentSource,
    CircuitNodeSource,
    CircuitNodeSourceChildren,
    CircuitPortDeclarationSource,
    CircuitPortDeclarationSourceSet,
    CircuitWiringDirectiveSource,
    CircuitWiringDirectiveSourceSet,
)
from signalflow.models.diagnostics import (
    Diagnostic,
    DiagnosticLevel,
    DiagnosticPhase,
    DiagnosticSet,
    DiagnosticStack,
    diagnosticStack,
)
from signalflow.models.directional_orientation import (
    DirectionalOrientation,
    destinationSideForDirectionalOrientation_get,
    directionalOrientationResult_buildFromSides,
    sourceSideForDirectionalOrientation_get,
)
from signalflow.models.engine import EngineName
from signalflow.models.grid_route import (
    RoutingZoneGridRouteSolveKind,
    RoutingZoneGridSolvedRoute,
    RoutingZoneGridSolvedRouteSet,
    routingZoneGridSolvedRouteResult_build,
    routingZoneGridSolvedRouteSetResult_build,
)
from signalflow.models.interconnect_route import (
    RoutingZoneInterconnectRouteSolveKind,
    RoutingZoneInterconnectSolvedRoute,
    RoutingZoneInterconnectSolvedRouteSet,
    routingZoneInterconnectSolvedRouteResult_build,
    routingZoneInterconnectSolvedRouteSetResult_build,
)
from signalflow.models.result import (
    Result,
    ResultErr,
    ResultOk,
    result_isErrCheck,
    result_isOkCheck,
    resultErr_build,
    resultOk_build,
)
from signalflow.models.route_obligation import (
    CallRouteObligation,
    CallRouteObligationSet,
    ChipInternalRouteObligation,
    ChipInternalRouteObligationSet,
    RouteObligationScope,
    RouteObligationSet,
    ZoneLocalGeometryKind,
    callRouteObligationSetResult_build,
    chipInternalRouteObligationSetResult_build,
    routeObligationSetResult_build,
)
from signalflow.models.routing_owner import (
    ChipLocalRoutingOwner,
    RoutingOwnerId,
    chipLocalRoutingOwner_build,
)
from signalflow.models.routing_zone import (
    ChipPlacement,
    ChipPlacementSet,
    GridCoord,
    RoutingLaneAttachmentSense,
    RoutingZone,
    RoutingZoneAttachmentPolicy,
    RoutingZoneChannelSense,
    RoutingZoneFrame,
    RoutingZoneId,
    RoutingZoneInterconnect,
    RoutingZoneInterconnectAxis,
    RoutingZoneInterconnectFrame,
    RoutingZoneInterconnectId,
    RoutingZoneRegion,
    RoutingZoneRegionFrame,
    RoutingZoneRegionId,
    RoutingZoneRegionKind,
    RoutingZoneRegionSet,
    RoutingZoneRegionSide,
    RoutingZoneSense,
    chipPlacementSetResult_build,
    routingZoneDrawLines_build,
    routingZoneFrameResult_build,
    routingZoneInterconnectFrameResult_build,
    routingZoneInterconnectResult_build,
    routingZoneRegionFrameResult_build,
    routingZoneRegionResult_build,
    routingZoneRegionSetResult_build,
    routingZoneResult_build,
)
from signalflow.models.routing_zone_grid import (
    RoutingZoneGrid,
    RoutingZoneGridPathPolicy,
    RoutingZoneInterconnectSet,
    RoutingZonePath,
    RoutingZoneSet,
    routingZoneGridResult_build,
    routingZoneInterconnectSetResult_build,
    routingZonePathResult_build,
    routingZoneSetResult_build,
)
from signalflow.models.zone_route import (
    RoutingZoneLocalRouteSolveKind,
    RoutingZoneLocalSolvedRoute,
    RoutingZoneLocalSolvedRouteSet,
    RoutingZoneRoutePoint,
    routingZoneLocalSolvedRouteResult_build,
    routingZoneLocalSolvedRouteSetResult_build,
    routingZoneRoutePointResult_build,
)

__all__: list[str] = [
    "RoutingZoneAssignment",
    "RoutingZoneAssignmentSet",
    "RoutingZoneLayer",
    "RoutingZoneLayerSet",
    "routingZoneAssignmentSetResult_build",
    "routingZoneLayerSetResult_build",
    "routingZoneLayerSetResult_buildFromCircuitDocument",
    "CardinalSide",
    "DirectionalOrientation",
    "Chip",
    "ChipId",
    "ChipInternalWiringDirective",
    "ChipInternalWiringDirectiveSet",
    "ChipIo",
    "ChipIoInput",
    "ChipIoInternalWiring",
    "ChipPortDeclaration",
    "ChipPortDeclarationSet",
    "ChipRef",
    "ChipTerminal",
    "ChipLocalRoutingOwner",
    "ChipTerminalRef",
    "ChipTerminalSet",
    "ChipTerminalSide",
    "chipDrawLines_build",
    "chipInternalWiringDirectiveResult_build",
    "chipInternalWiringDirectiveSetResult_build",
    "chipPortDeclarationResult_build",
    "chipPortDeclarationSetResult_build",
    "chipResult_build",
    "chipTerminalRef_build",
    "chipTerminalSetResult_build",
    "ChipInternalRouteClass",
    "ChipInternalRouteDirectiveSpec",
    "ChipInternalRouteOrientation",
    "ChipInternalRouteSemantics",
    "ChipInternalRouteSolveKind",
    "ChipInternalSolvedRoute",
    "ChipInternalSolvedRouteSet",
    "chipInternalRouteDirectiveSpecResult_build",
    "chipInternalSolvedRouteResult_build",
    "chipInternalSolvedRouteSetResult_build",
    "CircuitCall",
    "CircuitCallSet",
    "CircuitChipSet",
    "CircuitDocument",
    "CircuitDocumentSource",
    "CircuitNodeSource",
    "CircuitNodeSourceChildren",
    "CircuitPortDeclarationSource",
    "CircuitPortDeclarationSourceSet",
    "CircuitWiringDirectiveSource",
    "CircuitWiringDirectiveSourceSet",
    "CircuitChipIoInputSource",
    "CircuitChipIoInternalWiringSource",
    "CircuitChipIoSource",
    "circuitCallSetResult_build",
    "circuitChipSetResult_build",
    "circuitDocumentResult_build",
    "destinationSideForDirectionalOrientation_get",
    "Diagnostic",
    "DiagnosticLevel",
    "DiagnosticPhase",
    "DiagnosticSet",
    "DiagnosticStack",
    "EngineName",
    "RoutingZoneGridRouteSolveKind",
    "RoutingZoneGridSolvedRoute",
    "RoutingZoneGridSolvedRouteSet",
    "routingZoneGridSolvedRouteResult_build",
    "routingZoneGridSolvedRouteSetResult_build",
    "RoutingZoneInterconnectRouteSolveKind",
    "RoutingZoneInterconnectSolvedRoute",
    "RoutingZoneInterconnectSolvedRouteSet",
    "routingZoneInterconnectSolvedRouteResult_build",
    "routingZoneInterconnectSolvedRouteSetResult_build",
    "CallRouteObligation",
    "CallRouteObligationSet",
    "ChipInternalRouteObligation",
    "ChipInternalRouteObligationSet",
    "RouteObligationScope",
    "RouteObligationSet",
    "ZoneLocalGeometryKind",
    "callRouteObligationSetResult_build",
    "chipInternalRouteObligationSetResult_build",
    "routeObligationSetResult_build",
    "ChipPlacement",
    "ChipPlacementSet",
    "chipPlacementSetResult_build",
    "GridCoord",
    "Result",
    "ResultErr",
    "ResultOk",
    "RoutingLaneAttachmentSense",
    "RoutingZone",
    "RoutingZoneAttachmentPolicy",
    "RoutingZoneChannelSense",
    "RoutingZoneFrame",
    "routingZoneFrameResult_build",
    "RoutingZoneGrid",
    "RoutingZoneGridPathPolicy",
    "routingZoneGridResult_build",
    "RoutingZoneId",
    "RoutingZoneInterconnect",
    "RoutingZoneInterconnectAxis",
    "RoutingZoneInterconnectFrame",
    "routingZoneInterconnectFrameResult_build",
    "RoutingZoneInterconnectId",
    "routingZoneInterconnectSetResult_build",
    "routingZoneInterconnectResult_build",
    "RoutingZoneInterconnectSet",
    "RoutingZonePath",
    "routingZonePathResult_build",
    "RoutingZoneRegion",
    "RoutingZoneRegionFrame",
    "routingZoneRegionFrameResult_build",
    "RoutingZoneRegionId",
    "RoutingZoneRegionKind",
    "RoutingZoneRegionSet",
    "routingZoneRegionResult_build",
    "routingZoneRegionSetResult_build",
    "RoutingZoneRegionSide",
    "RoutingOwnerId",
    "routingZoneDrawLines_build",
    "RoutingZoneSense",
    "routingZoneResult_build",
    "RoutingZoneSet",
    "routingZoneSetResult_build",
    "RoutingZoneLocalRouteSolveKind",
    "RoutingZoneLocalSolvedRoute",
    "RoutingZoneLocalSolvedRouteSet",
    "RoutingZoneRoutePoint",
    "routingZoneLocalSolvedRouteResult_build",
    "routingZoneLocalSolvedRouteSetResult_build",
    "routingZoneRoutePointResult_build",
    "diagnosticStack",
    "directionalOrientationResult_buildFromSides",
    "chipLocalRoutingOwner_build",
    "resultErr_build",
    "resultOk_build",
    "result_isErrCheck",
    "result_isOkCheck",
    "sourceSideForDirectionalOrientation_get",
]
